import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Gem, PackageOpen, Repeat2, ScrollText, Zap } from 'lucide-react';
import './index.css';
import { api, tokenStore } from './lib/api';
import type { Case, History, InventoryItem, Item, Rarity, User } from './types/api';
import { ItemCard } from './components/ItemCard';
import { Layout } from './components/Layout';
import { rarityLabel } from './lib/rarity';

function useAsync<T>(loader: () => Promise<T>, deps: React.DependencyList) {
  const [data, setData] = useState<T | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { let alive = true; setLoading(true); loader().then(v => alive && setData(v)).catch(e => alive && setError(e.message)).finally(() => alive && setLoading(false)); return () => { alive = false }; }, deps);
  return { data, error, loading, setData };
}

function Auth({ setUser, setPage }: { setUser:(u:User)=>void; setPage:(p:string)=>void }) {
  const [mode,setMode]=useState<'login'|'register'>('login'); const [error,setError]=useState('');
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); const f=new FormData(e.currentTarget); try{const res=await api<{user:User;token:string}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify(Object.fromEntries(f))}); tokenStore.set(res.token); setUser(res.user); setPage('home')}catch(err){setError((err as Error).message)}}
  return <section className="mx-auto max-w-md rounded-[2rem] border border-white/10 bg-white/10 p-8 shadow-neon"><h1 className="text-3xl font-black">{mode==='login'?'Вход':'Регистрация'}</h1><form onSubmit={submit} className="mt-6 space-y-4">{mode==='register'&&<input name="username" placeholder="Username" className="w-full rounded-2xl bg-black/40 p-3"/>}<input name="email" placeholder="Email" defaultValue="player@example.com" className="w-full rounded-2xl bg-black/40 p-3"/><input name="password" type="password" placeholder="Password" defaultValue="password123" className="w-full rounded-2xl bg-black/40 p-3"/><button className="w-full rounded-2xl bg-gold p-3 font-black text-black">Continue</button></form>{error&&<p className="mt-3 text-red-300">{error}</p>}<button onClick={()=>setMode(mode==='login'?'register':'login')} className="mt-4 text-cyan-300">Switch mode</button></section>
}

function Home({ setPage }: { setPage:(p:string)=>void }) {
  const cases = useAsync<Case[]>(()=>api('/cases'), []); const history = useAsync<History[]>(()=>api('/history').catch(()=>[]), []);
  return <div className="space-y-12"><section className="grid items-center gap-8 py-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="mb-4 inline-flex rounded-full border border-gold/40 bg-gold/10 px-4 py-2 text-gold">Premium virtual CS-style case arena</p><h1 className="text-5xl font-black leading-tight md:text-7xl">Открывай кейсы, делай <span className="text-cyan-300">Upgrade</span> и собирай Contract.</h1><p className="mt-6 max-w-2xl text-lg text-slate-300">Тёмный esports MVP с backend-расчётом шансов, JWT, Prisma и виртуальными монетами без вывода реальных денег.</p><div className="mt-8 flex flex-wrap gap-4"><button onClick={()=>setPage('cases')} className="rounded-2xl bg-gold px-6 py-4 font-black text-black">Начать открывать</button><button onClick={()=>setPage('upgrade')} className="rounded-2xl border border-cyan-300/40 px-6 py-4 text-cyan-200">Upgrade</button><button onClick={()=>setPage('contract')} className="rounded-2xl border border-fuchsia-300/40 px-6 py-4 text-fuchsia-200">Contract</button></div></div><div className="rounded-[2.5rem] border border-white/10 bg-white/10 p-5 shadow-neon"><div className="rounded-[2rem] bg-gradient-to-br from-amber-400 via-red-500 to-cyan-400 p-1"><div className="rounded-[1.8rem] bg-night p-8"><Gem className="h-24 w-24 text-gold"/><p className="mt-8 text-3xl font-black">Dragon Case</p><p className="text-slate-300">Neon drops · roulette animation · rare special items</p></div></div></div></section><Section title="Популярные кейсы">{cases.loading?'Loading...':cases.data?.slice(0,5).map(c=><CaseCard key={c.id} c={c} onOpen={()=>setPage(`case:${c.id}`)}/>)}</Section><Section title="Режимы"><Mode icon={<PackageOpen/>} title="Cases"/><Mode icon={<Zap/>} title="Upgrade"/><Mode icon={<ScrollText/>} title="Contract"/></Section><Section title="Последние выигрыши">{history.data?.slice(0,6).map(h=><div key={h.id} className="rounded-3xl border border-white/10 bg-white/5 p-4"><p className="font-bold">{h.title}</p><p className="text-sm text-slate-400">{new Date(h.createdAt).toLocaleString()}</p></div>)}</Section></div>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="mb-5 text-3xl font-black">{title}</h2><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-5">{children}</div></section>}
function Mode({icon,title}:{icon:React.ReactNode;title:string}){return <div className="rounded-3xl border border-white/10 bg-white/5 p-6">{icon}<h3 className="mt-4 text-2xl font-black">{title}</h3><p className="text-slate-400">Backend verified virtual gameplay.</p></div>}
function CaseCard({c,onOpen}:{c:Case;onOpen:()=>void}){return <button onClick={onOpen} className="rounded-3xl border border-white/10 bg-slate-950/70 p-4 text-left hover:border-gold"><img src={c.imageUrl} className="h-32 w-full rounded-2xl object-cover"/><h3 className="mt-4 text-xl font-black">{c.name}</h3><p className="text-gold">{c.price} coins</p></button>}

function Cases({ page, refreshMe, setPage }: { page:string; refreshMe:()=>void; setPage:(p:string)=>void }) { const cases=useAsync<Case[]>(()=>api('/cases'), []); const id=page.startsWith('case:')?page.split(':')[1]:''; const selected=cases.data?.find(c=>c.id===id); const [win,setWin]=useState<InventoryItem|null>(null); const [err,setErr]=useState(''); async function open(){try{setErr(''); const res=await api<{inventoryItem:InventoryItem}>(`/cases/${selected!.id}/open`,{method:'POST'}); setWin(res.inventoryItem); refreshMe()}catch(e){setErr((e as Error).message)}} if(cases.loading)return <p>Loading cases...</p>; if(selected)return <div><button onClick={()=>setPage('cases')} className="text-cyan-300">← Back</button><div className="mt-4 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[2rem] border border-white/10 bg-white/10 p-6"><img src={selected.imageUrl} className="rounded-3xl"/><h1 className="mt-5 text-4xl font-black">{selected.name}</h1><p className="text-slate-300">{selected.description}</p><button onClick={open} className="mt-6 w-full rounded-2xl bg-gold p-4 font-black text-black">Открыть за {selected.price}</button>{err&&<p className="mt-3 text-red-300">{err}</p>}</div><div><div className="mb-5 overflow-hidden rounded-3xl border border-white/10 bg-black/40 p-4"><div className="roulette flex gap-3">{[...selected.items,...selected.items].slice(0,14).map((ci,i)=><img key={ci.id+i} src={ci.item.imageUrl} className="h-24 w-40 rounded-xl object-cover"/>)}</div></div>{win&&<div className="mb-5 rounded-3xl border border-gold bg-gold/10 p-5"><p className="text-gold">Выпало</p><ItemCard item={win}/></div>}<Section title="Содержимое кейса">{selected.items.map(ci=><div key={ci.id}><ItemCard item={ci.item}/><p className="mt-1 text-center text-sm text-slate-400">Chance {ci.chance.toFixed(1)}</p></div>)}</Section></div></div></div>; return <Section title="Все кейсы">{cases.data?.map(c=><CaseCard key={c.id} c={c} onOpen={()=>setPage(`case:${c.id}`)} />)}</Section> }

function Inventory({ refreshMe }: { refreshMe:()=>void }) { const inv=useAsync<InventoryItem[]>(()=>api('/inventory'), []); const [q,setQ]=useState(''); const [rarity,setRarity]=useState(''); async function sell(id:string){await api(`/inventory/${id}/sell`,{method:'POST'}); inv.setData(inv.data!.filter(i=>i.id!==id)); refreshMe()} const filtered=useMemo(()=>inv.data?.filter(i=>(!q||`${i.item.weapon} ${i.item.skin}`.toLowerCase().includes(q.toLowerCase()))&&(!rarity||i.item.rarity===rarity)),[inv.data,q,rarity]); return <div><h1 className="text-4xl font-black">Инвентарь</h1><div className="my-5 flex flex-wrap gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search" className="rounded-2xl bg-white/10 p-3"/><select value={rarity} onChange={e=>setRarity(e.target.value)} className="rounded-2xl bg-white/10 p-3"><option value="">All rarity</option>{Object.entries(rarityLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="grid gap-4 md:grid-cols-3 lg:grid-cols-4">{filtered?.map(i=><ItemCard key={i.id} item={i} action={<button onClick={(e)=>{e.stopPropagation();sell(i.id)}} className="w-full rounded-xl bg-white/10 p-2 text-sm">Sell</button>}/>)}</div></div> }

function Upgrade({ refreshMe }: { refreshMe:()=>void }) { const inv=useAsync<InventoryItem[]>(()=>api('/inventory'), []); const items=useAsync<Item[]>(()=>api('/items'), []); const [src,setSrc]=useState<InventoryItem>(); const [target,setTarget]=useState<Item>(); const [result,setResult]=useState(''); const chance=src&&target&&target.price>src.item.price?Math.min(src.item.price/target.price*.9,.75):0; async function run(){const r=await api<{success:boolean}>(`/upgrade`,{method:'POST',body:JSON.stringify({inventoryItemId:src!.id,targetItemId:target!.id})}); setResult(r.success?'SUCCESS — new item added':'FAILED — source item burned'); refreshMe()} return <div><h1 className="text-4xl font-black">Upgrade</h1><p className="mt-2 text-slate-400">Шанс = цена исходного / цена целевого × 0.9, максимум 75%.</p><div className="mt-6 grid gap-6 lg:grid-cols-2"><Panel title="Ваш предмет">{inv.data?.map(i=><ItemCard key={i.id} item={i} selected={src?.id===i.id} onClick={()=>setSrc(i)}/>)}</Panel><Panel title="Цель">{items.data?.filter(i=>!src||i.price>src.item.price).slice(0,20).map(i=><ItemCard key={i.id} item={i} selected={target?.id===i.id} onClick={()=>setTarget(i)}/>)}</Panel></div><div className="sticky bottom-4 mt-6 rounded-3xl border border-cyan-300/30 bg-night/90 p-5 backdrop-blur"><p className="text-2xl font-black">Chance {(chance*100).toFixed(1)}%</p><button disabled={!chance} onClick={run} className="mt-3 rounded-2xl bg-cyan-300 px-6 py-3 font-black text-black disabled:opacity-40">Run upgrade</button>{result&&<span className="ml-4 text-gold">{result}</span>}</div></div>}
function Contract({ refreshMe }: { refreshMe:()=>void }) { const inv=useAsync<InventoryItem[]>(()=>api('/inventory'), []); const [ids,setIds]=useState<string[]>([]); const [reward,setReward]=useState<InventoryItem>(); function toggle(id:string){setIds(v=>v.includes(id)?v.filter(x=>x!==id):v.length<10?[...v,id]:v)} async function run(){const r=await api<{inventoryItem:InventoryItem}>('/contract',{method:'POST',body:JSON.stringify({inventoryItemIds:ids})}); setReward(r.inventoryItem); refreshMe()} return <div><h1 className="text-4xl font-black">Contract</h1><p className="text-slate-400">Выберите ровно 10 предметов для новой награды близкой или чуть большей стоимости.</p><div className="my-5 rounded-3xl border border-fuchsia-300/20 bg-white/5 p-5">Selected {ids.length}/10 <button disabled={ids.length!==10} onClick={run} className="ml-4 rounded-2xl bg-fuchsia-300 px-5 py-2 font-black text-black disabled:opacity-40">Complete</button></div>{reward&&<div className="mb-5"><h2 className="text-2xl font-black text-gold">Contract reward</h2><ItemCard item={reward}/></div>}<div className="grid gap-4 md:grid-cols-3 lg:grid-cols-5">{inv.data?.map(i=><ItemCard key={i.id} item={i} selected={ids.includes(i.id)} onClick={()=>toggle(i.id)}/>)}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div><h2 className="mb-4 text-2xl font-black">{title}</h2><div className="grid gap-4 md:grid-cols-2">{children}</div></div>}
function Admin(){return <div className="rounded-3xl border border-white/10 bg-white/5 p-8"><h1 className="text-4xl font-black">Admin MVP</h1><p className="mt-3 text-slate-300">REST routes are ready: create/edit items, create/edit cases, assign drop chances and top up users. Use the API with an admin JWT from admin@example.com / password123.</p></div>}
function App(){const [page,setPageState]=useState(location.hash.slice(1)||'home'); const [user,setUser]=useState<User|null>(null); const refreshMe=()=>api<User>('/me').then(setUser).catch(()=>setUser(null)); useEffect(()=>{if(tokenStore.get())refreshMe()},[]); function setPage(p:string){location.hash=p;setPageState(p)} let content= page==='auth'?<Auth setUser={setUser} setPage={setPage}/>:page==='home'?<Home setPage={setPage}/>:page.startsWith('case')||page==='cases'?<Cases page={page} refreshMe={refreshMe} setPage={setPage}/>:page==='inventory'?<Inventory refreshMe={refreshMe}/>:page==='upgrade'?<Upgrade refreshMe={refreshMe}/>:page==='contract'?<Contract refreshMe={refreshMe}/>:<Admin/>; return <Layout user={user} page={page} setPage={setPage} onLogout={()=>{tokenStore.clear();setUser(null)}}>{content}</Layout>}

createRoot(document.getElementById('root')!).render(<App/>);
